defaults:
  - config  # Reference the main configuration

name: test_config

env:
  wrapper:
    use: true

train:
  n_envs: 1
  steer_penalty_actions_len: 50
  steer_penalty_th: 20
  steer_penalty_reward: -5

eval:
  eval_freq: 1000
algo_name: PPO
algo_cfg:
  n_steps: 2048
  n_epochs: 10
